<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>CourseToIcal.Core</RootNamespace>
    <AssemblyName>CourseToIcal.Core</AssemblyName>
  </PropertyGroup>
</Project>
