<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>CourseToIcal.App</RootNamespace>
    <AssemblyName>CourseToIcal</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CourseToIcal.Core\CourseToIcal.Core.csproj" />
  </ItemGroup>
</Project>
